org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod Metadata
mod_id=create_dimension
mod_name=Create: Dimension, Steamworks Realm
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.reggarf.mods
mod_authors=Reggarf
mod_description=Create: Dimension, Steamworks Realm introduces a brand-new mining-focused dimension, designed for automation and large-scale resource extraction. This world is filled with rich veins of ores, mechanical landscapes, and steam-powered environments, perfect for players looking to expand their Create Mod builds with advanced mining systems.


# Forge 1.20.1 Properties
forge_1_20_1_minecraft_version=1.20.1
forge_1_20_1_minecraft_version_range=[1.20.1,1.21)
forge_1_20_1_forge_version=47.4.0
forge_1_20_1_forge_version_range=[47,)
forge_1_20_1_loader_version_range=[47,)
forge_1_20_1_mapping_channel=official
forge_1_20_1_mapping_version=1.20.1
forge_1_20_1_create_version=6.0.7-281
forge_1_20_1_ponder_version=1.0.91
forge_1_20_1_flywheel_version=1.0.5
forge_1_20_1_registrate_version=MC1.20-1.3.3

# NeoForge 1.21.1 Properties
neoforge_1_21_1_minecraft_version=1.21.1
neoforge_1_21_1_minecraft_version_range=[1.21.1,1.22)
neoforge_1_21_1_neoforge_version=21.1.219
neoforge_1_21_1_loader_version_range=[4,)
neoforge_1_21_1_create_version=6.0.10-280
neoforge_1_21_1_ponder_version=1.0.82
neoforge_1_21_1_flywheel_version=1.0.6
neoforge_1_21_1_registrate_version=MC1.21-1.3.0+67
